### ISSUE TITLE
could it work on xpenology with proxmox

### ISSUE THREAD

**Issue by delta-whiplash** [dskad/qemu-ga-container#6]
Hello do you think this container could display all ip of my xpenology NAS VM

**Comment by dskad** [comment]
It should work in Proxmox VMs, as long as you enable the "QEMU Guest Agent"  option in your VM. 

This creates the /dev/virtio-ports/org.qemu.guest_agent.0 device that the guest agent in this container can talk to and report the IP addresses back to Proxmox. You'll need to run this container in each of your VMs. 

I believe guest agent support is enabled by default in synology/xpenology and this container should work there also.

**Comment by delta-whiplash** [comment]
Ok nice and If I enable qemu-guest-agent on proxmox could I stop the VM with acpi ?

**Comment by dskad** [comment]
QEMU/Proxmox use ACPI by default to send the shutdown signal to the VMs, but the VM OS needs to support ACPI to be able to listen for those signals. If it doesn't support ACPI, both Proxmox and QEMU will fall back to using the QEMU Guest Agent. I know CoreOS and possibly Flatcar Linux don't listen to ACPI events.

To use this container to shutdown the host VM, the container will have to run with the privileged  option and bind mounting  parts of the host into the container. 

For a systemd host VM, you'll need to mount /var/run/dbus/system_bus_socket and /sys/fs/cgroup as well as the systemctl and shutdown command. The QEMU agent calls the shutdown command. The problem is that this container is based off of the Alpine image, so it will be missing libraries that the mounted systemctl was linked with on the host OS. So those libraries will need to be mounted into the container as well.

On Fedora CoreOS 37.20230303.2.0, these are the needed libraries: 
````bash
[core@coreos ~]$ ldd /bin/systemctl 
        linux-vdso.so.1 (0x00007ffd2117d000)
        libsystemd-shared-251.11-2.fc37.so => /usr/lib/systemd/libsystemd-shared-251.11-2.fc37.so (0x00007f8d1d600000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8d1da85000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8d1d423000)
        libacl.so.1 => /lib64/libacl.so.1 (0x00007f8d1da7b000)
        libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f8d1da42000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f8d1da36000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f8d1d9fc000)
        libkmod.so.2 => /lib64/libkmod.so.2 (0x00007f8d1d9de000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f8d1d9bb000)
        libmount.so.1 => /lib64/libmount.so.1 (0x00007f8d1d974000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f8d1ce00000)
        libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007f8d1d2ee000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007f8d1d960000)
        libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007f8d1d2ce000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f8d1d2a1000)
        libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f8d1cd4b000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f8d1d26d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f8d1cc6b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8d1daf1000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f8d1d956000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f8d1d253000)
        libffi.so.8 => /lib64/libffi.so.8 (0x00007f8d1d247000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f8d1cc3d000)
        libeconf.so.0 => /lib64/libeconf.so.0 (0x00007f8d1d23c000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f8d1cba0000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f8d1d230000)
````

So I'll need the /lib64 folder (this doesn't exist in the alpine image) and /usr/lib/systemd/libsystemd-shared-251.11-2.fc37.so

On CoreOS, running this container with these options will allow the agent to shutdown/reboot the host VM, get the host network info, the host OS info and the host's hostname. 

````bash
sudo docker run --rm --name qemu-ga \
  -v /dev:/dev \
  -v /etc/os-release:/etc/os-release:ro \
  -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket \
  -v /sys/fs/cgroup:/sys/fs/cgroup \
  -v /usr/lib/systemd:/usr/lib/systemd \
  -v /lib64:/lib64 \
  -v /bin/systemctl:/bin/systemctl \
  -v /sbin/shutdown:/sbin/shutdown \
  --privileged \
  --uts=host \
  --net=host \
  docker.io/danskadra/qemu-ga -v
````

You'll likely have to modify the locations of the mounted library directories based on the output of `ldd` on your VM, if you're not running Fedora CoreOS. You may need to mount each library individually if `ldd` is showing libraries in /usr/lib, for example. overwriting the whole /usr/lib in the container, may break the container.
